//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaService.Test.TTTService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/MangaService.Model")]
    public enum Category : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatestUpdated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MostPopular = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manga", Namespace="http://schemas.datacontract.org/2004/07/MangaService.Model")]
    [System.SerializableAttribute()]
    public partial class Manga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MangaService.Test.TTTService.Chapter[] ChapterListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MangaService.Test.TTTService.MangaInfo MangaInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MangaService.Test.TTTService.Chapter[] ChapterList {
            get {
                return this.ChapterListField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterListField, value) != true)) {
                    this.ChapterListField = value;
                    this.RaisePropertyChanged("ChapterList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MangaService.Test.TTTService.MangaInfo MangaInfo {
            get {
                return this.MangaInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.MangaInfoField, value) != true)) {
                    this.MangaInfoField = value;
                    this.RaisePropertyChanged("MangaInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MangaInfo", Namespace="http://schemas.datacontract.org/2004/07/MangaService.Model")]
    [System.SerializableAttribute()]
    public partial class MangaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri CoverImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GenreListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatestChapterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LatestUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MangaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri MangaUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri CoverImage {
            get {
                return this.CoverImageField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverImageField, value) != true)) {
                    this.CoverImageField = value;
                    this.RaisePropertyChanged("CoverImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GenreListName {
            get {
                return this.GenreListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreListNameField, value) != true)) {
                    this.GenreListNameField = value;
                    this.RaisePropertyChanged("GenreListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatestChapter {
            get {
                return this.LatestChapterField;
            }
            set {
                if ((object.ReferenceEquals(this.LatestChapterField, value) != true)) {
                    this.LatestChapterField = value;
                    this.RaisePropertyChanged("LatestChapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LatestUpdatedDate {
            get {
                return this.LatestUpdatedDateField;
            }
            set {
                if ((this.LatestUpdatedDateField.Equals(value) != true)) {
                    this.LatestUpdatedDateField = value;
                    this.RaisePropertyChanged("LatestUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MangaName {
            get {
                return this.MangaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MangaNameField, value) != true)) {
                    this.MangaNameField = value;
                    this.RaisePropertyChanged("MangaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri MangaUri {
            get {
                return this.MangaUriField;
            }
            set {
                if ((object.ReferenceEquals(this.MangaUriField, value) != true)) {
                    this.MangaUriField = value;
                    this.RaisePropertyChanged("MangaUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRating {
            get {
                return this.MaxRatingField;
            }
            set {
                if ((this.MaxRatingField.Equals(value) != true)) {
                    this.MaxRatingField = value;
                    this.RaisePropertyChanged("MaxRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chapter", Namespace="http://schemas.datacontract.org/2004/07/MangaService.Model")]
    [System.SerializableAttribute()]
    public partial class Chapter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChapterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri ChapterUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDownloadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChapterName {
            get {
                return this.ChapterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterNameField, value) != true)) {
                    this.ChapterNameField = value;
                    this.RaisePropertyChanged("ChapterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ChapterUri {
            get {
                return this.ChapterUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterUriField, value) != true)) {
                    this.ChapterUriField = value;
                    this.RaisePropertyChanged("ChapterUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDownloaded {
            get {
                return this.IsDownloadedField;
            }
            set {
                if ((this.IsDownloadedField.Equals(value) != true)) {
                    this.IsDownloadedField = value;
                    this.RaisePropertyChanged("IsDownloaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TTTService.IMangaService")]
    public interface IMangaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMangaService/LoadMoreMangaFast", ReplyAction="http://tempuri.org/IMangaService/LoadMoreMangaFastResponse")]
        MangaService.Test.TTTService.Manga[] LoadMoreMangaFast(MangaService.Test.TTTService.Category category, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMangaService/LoadMoreMangaFast", ReplyAction="http://tempuri.org/IMangaService/LoadMoreMangaFastResponse")]
        System.Threading.Tasks.Task<MangaService.Test.TTTService.Manga[]> LoadMoreMangaFastAsync(MangaService.Test.TTTService.Category category, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMangaService/LoadMoreManga", ReplyAction="http://tempuri.org/IMangaService/LoadMoreMangaResponse")]
        MangaService.Test.TTTService.Manga[] LoadMoreManga(MangaService.Test.TTTService.Category category, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMangaService/LoadMoreManga", ReplyAction="http://tempuri.org/IMangaService/LoadMoreMangaResponse")]
        System.Threading.Tasks.Task<MangaService.Test.TTTService.Manga[]> LoadMoreMangaAsync(MangaService.Test.TTTService.Category category, int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMangaServiceChannel : MangaService.Test.TTTService.IMangaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MangaServiceClient : System.ServiceModel.ClientBase<MangaService.Test.TTTService.IMangaService>, MangaService.Test.TTTService.IMangaService {
        
        public MangaServiceClient() {
        }
        
        public MangaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MangaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MangaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MangaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MangaService.Test.TTTService.Manga[] LoadMoreMangaFast(MangaService.Test.TTTService.Category category, int count) {
            return base.Channel.LoadMoreMangaFast(category, count);
        }
        
        public System.Threading.Tasks.Task<MangaService.Test.TTTService.Manga[]> LoadMoreMangaFastAsync(MangaService.Test.TTTService.Category category, int count) {
            return base.Channel.LoadMoreMangaFastAsync(category, count);
        }
        
        public MangaService.Test.TTTService.Manga[] LoadMoreManga(MangaService.Test.TTTService.Category category, int count) {
            return base.Channel.LoadMoreManga(category, count);
        }
        
        public System.Threading.Tasks.Task<MangaService.Test.TTTService.Manga[]> LoadMoreMangaAsync(MangaService.Test.TTTService.Category category, int count) {
            return base.Channel.LoadMoreMangaAsync(category, count);
        }
    }
}
